export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_SIGNOUT = 'AUTH_SIGNOUT';

export const LOADING_PROGRESS = 'LOADING_PROGRESS';
export const PROFILE_LOADING_PROGRESS = 'PROFILE_LOADING_PROGRESS';
export const ARTICLE_LOADING_PROGRESS = 'ARTICLE_LOADING_PROGRESS';
export const BOOKMARKS_LOADING_PROGRESS = 'BOOKMARKS_LOADING_PROGRESS';

export const GET_MY_PROFILE_SUCCESS = 'GET_MY_PROFILE_SUCCESS';
export const GET_MY_PROFILE_ERROR = 'GET_MY_PROFILE_ERROR';
export const UPDATE_MY_PROFILE_SUCCESS = 'UPDATE_MY_PROFILE_SUCCESS';
export const UPDATE_MY_PROFILE_ERROR = 'UPDATE_MY_PROFILE_ERROR';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const FETCH_ALL_ARTICLES = 'FETCH_ALL_ARTICLES';
export const FETCH_SINGLE_ARTICLE = 'FETCH_SINGLE_ARTICLE';
export const CREATE_SINGLE_ARTICLE = 'CREATE_SINGLE_ARTICLE';
export const ERROR_FETCHING_ARTICLES = 'ERROR_FETCHING_ARTICLES';
export const DELETE_SINGLE_ARTICLE = 'DELETE_SINGLE_ARTICLE';

export const DISLIKE_ARTICLE = 'DISLIKE_ARTICLE';
export const LIKE_ARTICLE = 'LIKE_ARTICLE';
export const LIKE_DISLIKE_ERROR = 'LIKE_DISLIKE_ERROR';
export const GET_ARTICLE_DATA = 'GET_ARTICLE_DATA';

export const SET_PAGE = 'SET_PAGE';

export const UPDATE_ARTICLE_RATING = 'UPDATE_ARTICLE_RATING';
export const ARTICLE_RATING_UPDATED = 'ARTICLE_RATING_UPDATED';
export const ARTICLE_RATING_FAILED = 'ARTICLE_RATING_FAILED';

export const SEARCH_ARTICLES = 'SEARCH_ARTICLES';
export const FETCH_ALL_BOOKMARKS_SUCCESS = 'FETCH_ALL_BOOKMARKS_SUCCESS';
export const CREATE_SINGLE_BOOKMARK_SUCCESS = 'CREATE_SINGLE_BOOKMARK_SUCCESS';
export const DELETE_SINGLE_BOOKMARK_SUCCESS = 'DELETE_SINGLE_BOOKMARK_SUCCESS';
export const CREATE_SINGLE_BOOKMARK_ERROR = 'CREATE_SINGLE_BOOKMARK_ERROR';
export const DELETE_SINGLE_BOOKMARK_ERROR = 'DELETE_SINGLE_BOOKMARK_ERROR';
export const FETCH_ALL_BOOKMARKS_ERROR = 'FETCH_ALL_BOOKMARKS_ERROR';
export const UPDATE_MY_PROFILE_FOLLOW_SUCCESS = 'UPDATE_MY_PROFILE_FOLLOW_SUCCESS';
export const GET_SINGLE_PROFILE_SUCCESS = 'GET_SINGLE_PROFILE_SUCCESS';

export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const ERROR_FETCHING_COMMENTS = 'ERROR_FETCHING_COMMENTS';
export const FETCH_ALL_COMMENTS = 'FETCH_ALL_COMMENTS';

export const ERROR_FETCHING_REPLIES = 'ERROR_FETCHING_REPLIES';
export const FETCH_ALL_REPLIES = 'FETCH_ALL_REPLIES';

export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE';

export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE';

export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS';
export const EDIT_COMMENT_FAILURE = 'EDIT_COMMENT_FAILURE';

export const POST_REPLY_FAILURE = 'POST_REPLY_FAILURE';

export const GET_COMMENT_DATA = 'GET_COMMENT_DATA';
export const GET_COMMENT_ERROR = 'GET_COMMENT_ERROR';

export const STATS_LOADING_PROGRESS = 'STATS_LOADING_PROGRESS';
export const FETCH_ALL_MY_VIEWS = 'FETCH_ALL_MY_VIEWS';
export const FETCH_MY_ARTICLE_VIEWS = 'FETCH_MY_ARTICLE_VIEWS';
export const ERROR_FETCHING_STATS = 'ERROR_FETCHING_STATS';

export const NOTIFICATION_LIST_UPDATED = 'NOTIFICATION_LIST_UPDATED';
export const FRESH_NOTIFICATIONS_LIST = 'FRESH_NOTIFICATIONS_LIST';
export const RESET_NOTIFICATIONS_COUNT = 'RESET_NOTIFICATIONS_COUNT';

export const REPORT_ARTICLE = 'REPORT_ARTICLE';
export const REPORT_SUCCESS = 'REPORT_SUCCESS';
export const REPORT_FAILED = 'REPORT_FAILED';
export const LOADING_REPORT = 'LOADING_REPORT';
export const SHOW_MODAL = 'SHOW_MODAL';
