export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_SIGNOUT = 'AUTH_SIGNOUT';

export const LOADING_PROGRESS = 'LOADING_PROGRESS';
export const PROFILE_LOADING_PROGRESS = 'PROFILE_LOADING_PROGRESS';
export const ARTICLE_LOADING_PROGRESS = 'PROFILE_LOADING_PROGRESS';

export const GET_MY_PROFILE_SUCCESS = 'GET_MY_PROFILE_SUCCESS';
export const GET_MY_PROFILE_ERROR = 'GET_MY_PROFILE_ERROR';
export const UPDATE_MY_PROFILE_SUCCESS = 'UPDATE_MY_PROFILE_SUCCESS';
export const UPDATE_MY_PROFILE_ERROR = 'UPDATE_MY_PROFILE_ERROR';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const FETCH_ALL_ARTICLES = 'FETCH_ALL_ARTICLES';
export const FETCH_SINGLE_ARTICLE = 'FETCH_SINGLE_ARTICLE';
export const CREATE_SINGLE_ARTICLE = 'CREATE_SINGLE_ARTICLE';
export const ERROR_FETCHING_ARTICLES = 'ERROR_FETCHING_ARTICLES';
export const DELETE_SINGLE_ARTICLE = 'DELETE_SINGLE_ARTICLE';

export const DISLIKE_ARTICLE = 'DISLIKE_ARTICLE';
export const LIKE_ARTICLE = 'LIKE_ARTICLE';
export const LIKE_DISLIKE_ERROR = 'LIKE_DISLIKE_ERROR';
export const GET_ARTICLE_DATA = 'GET_ARTICLE_DATA';
export const SET_PAGE = 'SET_PAGE';
export const UPDATE_ARTICLE_RATING = 'UPDATE_ARTICLE_RATING';
export const ARTICLE_RATING_UPDATED = 'ARTICLE_RATING_UPDATED';
export const ARTICLE_RATING_FAILED = 'ARTICLE_RATING_FAILED';

export const SEARCH_ARTICLES = 'SEARCH_ARTICLES';
export const UPDATE_MY_PROFILE_FOLLOW_SUCCESS = 'UPDATE_MY_PROFILE_FOLLOW_SUCCESS';
export const GET_SINGLE_PROFILE_SUCCESS = 'GET_SINGLE_PROFILE_SUCCESS';

export const FETCH_ALL_BOOKMARKS = 'FETCH_ALL_BOOKMARKS';
export const CREATE_SINGLE_BOOKMARK = 'CREATE_SINGLE_BOOKMARK';
export const DELETE_SINGLE_BOOKMARK = 'DELETE_SINGLE_BOOKMARK';

export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const ERROR_FETCHING_COMMENTS = 'ERROR_FETCHING_COMMENTS';
export const FETCH_ALL_COMMENTS = 'FETCH_ALL_COMMENTS';

export const ERROR_FETCHING_REPLIES = 'ERROR_FETCHING_REPLIES';
export const FETCH_ALL_REPLIES = 'FETCH_ALL_REPLIES';

export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE';

export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE';

export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS';
export const EDIT_COMMENT_FAILURE = 'EDIT_COMMENT_FAILURE';

export const POST_REPLY_FAILURE = 'POST_REPLY_FAILURE';
