export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_SIGNOUT = 'AUTH_SIGNOUT';

export const LOADING_PROGRESS = 'LOADING_PROGRESS';

export const GET_MY_PROFILE_SUCCESS = 'GET_MY_PROFILE_SUCCESS';
export const GET_MY_PROFILE_ERROR = 'GET_MY_PROFILE_ERROR';
export const UPDATE_MY_PROFILE_SUCCESS = 'UPDATE_MY_PROFILE_SUCCESS';
export const UPDATE_MY_PROFILE_ERROR = 'UPDATE_MY_PROFILE_ERROR';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';


export const FETCH_ALL_ARTICLES = 'FETCH_ALL_ARTICLES';
export const FETCH_SINGLE_ARTICLE = 'FETCH_SINGLE_ARTICLE';
export const CREATE_SINGLE_ARTICLE = 'CREATE_SINGLE_ARTICLE';
export const ERROR_FETCHING_ARTICLES = 'ERROR_FETCHING_ARTICLES';
export const DELETE_SINGLE_ARTICLE = 'DELETE_SINGLE_ARTICLE';

export const SET_PAGE = 'SET_PAGE';
